import = ["C:/Users/Максим/.config/alacritty/github_light_high_contrast.toml"]

[env]
LC_CTYPE = "en_US.UTF-8"
TERM = "xterm-256color"

[shell]
program = "ubuntu"

[window]
opacity = 1
startup_mode = "Maximized"
dynamic_padding = false
dynamic_title = false
title = "Alacritty"

[window.padding]
x = 6
y = 6

[window.class]
general = "Alacritty"
instance = "Alacritty"

[font]
size = 14

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[font.offset]
x = 0
y = 0

[colors]
draw_bold_text_with_bright_colors = true

[colors.cursor]
text                  = "#B4BEFE"
cursor                = "#000000"

[colors.vi_mode_cursor]
text                  = "#1E1E2E"
cursor                = "#B4BEFE"

[cursor.style]
shape                 = "Block"
blinking              = "Always"

[cursor.vi_mode_style]
shape                 = "Block"
blinking              = "Off"

[cursor]
blink_interval        = 500
blink_timeout         = 0

